name: easylanche
description: Está com fome? triste com a falta de uma cantina na EAJ? Baixe já o Easylanche e descubra uma forma simples de achar comida no país EAJ

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  google_fonts: ^3.0.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  lottie: ^1.3.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  get_it: ^7.2.0
  mask_text_input_formatter: ^2.4.0
  flutter_secure_storage: ^6.0.0
  flutter_slidable: ^2.0.0
  url_launcher: ^6.1.6
  open_whatsapp: ^0.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1
  test: ^1.21.1
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

scripts:
  build_runner: flutter pub run build_runner watch --delete-conflicting-outputs --use-polling-watcher
  create_splash_dev: flutter pub run flutter_native_splash:create --flavor dev
  create_splash_hmlg: flutter pub run flutter_native_splash:create --flavor hmlg
  create_splash_prod: flutter pub run flutter_native_splash:create --flavor prod
  create_launcher_icon: flutter pub run flutter_launcher_icons:main
